#!/usr/bin/env bash
# macOS-specific setup
if [ -x "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x "/usr/local/bin/brew" ]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi
if [ -f "$HOME/.dot/files/bash/common/bashrc" ]; then
    . "$HOME/.dot/files/bash/common/bashrc"
fi
