#!/usr/bin/env bash
# macOS-specific Homebrew path
if [ -x "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
elif [ -x "/usr/local/bin/brew" ]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi
if [ -f "$HOME/.dot/files/bash/common/bash_profile" ]; then
    . "$HOME/.dot/files/bash/common/bash_profile"
fi
