export BASH_SILENCE_DEPRECATION_WARNING=1

# if running bash
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
    fi
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

export EDITOR=vim
