export BASH_SILENCE_DEPRECATION_WARNING=1

# if running bash
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
    fi
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ] ; then
    PATH="$HOME/bin/Sencha/Cmd:$HOME/.bin:$PATH"
fi

# add rbenv version of ruby if available
if [ -d "$HOME/.rbenv" ] ; then
    PATH="$HOME/.rbenv/versions/2.7.7/bin:$PATH"
    #PATH="$HOME/.rbenv/versions/3.2.2/bin:$PATH"
fi

export EDITOR=vim

# Check for Homebrew and setup environment
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jwaspin/google-cloud-sdk/path.bash.inc' ]; then . '/Users/jwaspin/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jwaspin/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/jwaspin/google-cloud-sdk/completion.bash.inc'; fi
