#!/usr/bin/env bash
script_path="${BASH_SOURCE[0]}"
while [ -L "$script_path" ]; do
    dir="$(cd -P "$(dirname "$script_path")" >/dev/null 2>&1 && pwd)"
    target="$(readlink "$script_path")"
    case "$target" in
        /*) script_path="$target" ;;
        *) script_path="$dir/$target" ;;
    esac
done
script_dir="$(cd -P "$(dirname "$script_path")" >/dev/null 2>&1 && pwd)"
source "$script_dir/../common/bash_profile"
