#terminal color
set -g default-terminal "xterm"
# remap prefix to control + a
set -g prefix 'C-a'
bind C-a send-prefix

# # vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# and now unbind keys
unbind Up     
unbind Down   
unbind Left   
unbind Right

set -g default-terminal "screen-256color"
